QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-lcouso'
main.py:35: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  button.setGeometry(self.sw*480, self.sh*450, self.sw*40, self.sh*20)
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
main.py:47: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  paint.drawEllipse(self.sw*270, self.sh*70, self.sw*450, self.sh*450)
tcgetpgrp failed: Not a tty
Please be more descriptive
HTTP Error for GET to https://api.spotify.com/v1/me/tracks returned 403 due to error
Traceback (most recent call last):
  File "/home/lcouso/.local/lib/python3.8/site-packages/spotipy/client.py", line 245, in _internal_call
    response.raise_for_status()
  File "/home/lcouso/.local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.spotify.com/v1/me/tracks?limit=50&offset=0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/users/lachi/PycharmProjects/FinalProject/LoadPage.py", line 59, in startProgressBar
    self.nextPg = PlaylistPg()
  File "/mnt/c/users/lachi/PycharmProjects/FinalProject/PlaylistGUI.py", line 17, in __init__
    self.initUI()
  File "/mnt/c/users/lachi/PycharmProjects/FinalProject/PlaylistGUI.py", line 26, in initUI
    self.mood_window()
  File "/mnt/c/users/lachi/PycharmProjects/FinalProject/PlaylistGUI.py", line 30, in mood_window
    Person.tracks = generatePlaylist()
  File "/mnt/c/users/lachi/PycharmProjects/FinalProject/PlaylistGenerator.py", line 12, in generatePlaylist
    user_songs = user.get_user_saved_tracks()
  File "/mnt/c/users/lachi/PycharmProjects/FinalProject/Spotipy.py", line 53, in get_user_saved_tracks
    items = self._user_client.current_user_saved_tracks(50, 50 * i)['items']
  File "/home/lcouso/.local/lib/python3.8/site-packages/spotipy/client.py", line 1226, in current_user_saved_tracks
    return self._get("me/tracks", limit=limit, offset=offset, market=market)
  File "/home/lcouso/.local/lib/python3.8/site-packages/spotipy/client.py", line 291, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/home/lcouso/.local/lib/python3.8/site-packages/spotipy/client.py", line 261, in _internal_call
    raise SpotifyException(
spotipy.exceptions.SpotifyException: http status: 403, code:-1 - https://api.spotify.com/v1/me/tracks?limit=50&offset=0: error, reason: None